apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  type: NodePort
  selector:
    app: mediawiki
  ports:
  - name: http
    port: 80
    protocol: TCP
