apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
~                         
